name: Vercel Deployment
on:
  push:
    branches: [main]
jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      - run: npm ci
      - run: npx playwright test